name: pet_care
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+17

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^5.0.0
  sizer: ^2.0.15
  get: ^4.6.1
  sqflite: ^2.2.8+4
  connectivity: ^3.0.6
  flutter_vector_icons: ^1.0.0
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.7+2
  image_cropper: ^1.4.1
  lottie: ^2.5.0
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.8
  omni_datetime_picker: ^1.0.7
  date_time_format: ^2.0.1
  top_snackbar_flutter: ^3.0.0+1
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  glassmorphism: ^3.0.0
  flutter_datetime_picker_plus: ^2.0.1
  google_mobile_ads: ^3.0.0
  timezone: ^0.9.2
  flutter_markdown: ^0.6.17+1
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^15.1.0+1
  http: ^1.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
 
  uses-material-design: true

  assets:
    - assets/image/
    - assets/
